version: '3'

services:
  backend:
    build: ./server
    ports:
      - '${BACKEND_PORT:-5000}:5000'
    environment:
      - NODE_ENV=$NODE_ENV
    depends_on:
      - db
    volumes:
      - ./server:/app
    networks:
      - app-network

  frontend:
    build: ./client
    ports:
      - '${FRONTEND_PORT:-3000}:3000'
    depends_on:
      - backend
    volumes:
      - ./client:/app
    networks:
      - app-network

  db:
    image: mongo:latest
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  app-network:
